version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend 
    ports:
      - "8080:8080" 
